# .github/workflows/cloudflare-pages.yml

name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions for the GitHub token to deploy to Cloudflare
permissions:
  contents: read
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build with Next.js
        run: bun run build

      - name: Build for Cloudflare Pages
        run: bun run pages:build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: .next
          path: .vercel/output/static # The output directory for next-on-pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: .next
          path: .vercel/output/static

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: wizdevtech-cms # The name of your project in Cloudflare
          directory: .vercel/output/static