"use client";

import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Progress } from "@/components/ui/progress";
import { 
  Wand2, 
  Sparkles, 
  Copy, 
  RefreshCw,
  FileText,
  Brain,
  Zap,
  Target,
  TrendingUp,
  Hash,
  MessageSquare,
  Settings,
  CheckCircle
} from "lucide-react";

interface ContentTemplate {
  id: string;
  name: string;
  description: string;
  prompts: string[];
}

interface GeneratedContent {
  id: string;
  title: string;
  content: string;
  excerpt: string;
  tags: string[];
  wordCount: number;
  readingTime: number;
  createdAt: Date;
  prompt: string;
  template: string;
}

interface AIContentGeneratorProps {
  onContentGenerated: (content: GeneratedContent) => void;
  onInsertToEditor: (content: GeneratedContent) => void;
  isLoading?: boolean;
}

export function AIContentGenerator({
  onContentGenerated,
  onInsertToEditor,
  isLoading = false
}: AIContentGeneratorProps) {
  const [activeTab, setActiveTab] = useState('generate');
  const [prompt, setPrompt] = useState('');
  const [contentType, setContentType] = useState('blog-post');
  const [tone, setTone] = useState('professional');
  const [length, setLength] = useState('medium');
  const [targetAudience, setTargetAudience] = useState('general');
  const [keywords, setKeywords] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedContent, setGeneratedContent] = useState<GeneratedContent[]>([]);

  const templates: ContentTemplate[] = [
    {
      id: 'blog-post',
      name: 'Blog Post',
      description: 'Engaging blog content with proper structure',
      prompts: [
        'Write a comprehensive blog post about [topic]',
        'Create an informative article about [topic] for [audience]',
        'Generate a blog post discussing [topic] with [tone] tone'
      ]
    },
    {
      id: 'article',
      name: 'Article',
      description: 'Well-researched article format',
      prompts: [
        'Write a detailed article about [topic]',
        'Create an informative piece on [topic]',
        'Generate an article covering [topic] with expert insights'
      ]
    },
    {
      id: 'social-media',
      name: 'Social Media',
      description: 'Short, engaging social media content',
      prompts: [
        'Create social media posts about [topic]',
        'Generate engaging tweets about [topic]',
        'Write Instagram captions for [topic]'
      ]
    },
    {
      id: 'product-description',
      name: 'Product Description',
      description: 'Compelling product descriptions',
      prompts: [
        'Write a product description for [product]',
        'Create compelling copy for [product]',
        'Generate marketing content for [product]'
      ]
    },
    {
      id: 'email-newsletter',
      name: 'Email Newsletter',
      description: 'Professional email content',
      prompts: [
        'Write a newsletter about [topic]',
        'Create an email campaign for [topic]',
        'Generate engaging email content about [topic]'
      ]
    }
  ];

  const generateContent = async () => {
    if (!prompt.trim()) return;
    
    setIsGenerating(true);
    
    // Simulate AI generation
    await new Promise(resolve => setTimeout(resolve, 3000));
    
    const mockContent: GeneratedContent = {
      id: Date.now().toString(),
      title: `AI Generated: ${prompt.substring(0, 50)}...`,
      content: `This is AI-generated content based on your prompt: "${prompt}". 

In a real implementation, this would be high-quality content generated by a language model. The content would be tailored to your specifications:

- Content Type: ${contentType}
- Tone: ${tone}
- Length: ${length}
- Target Audience: ${targetAudience}
- Keywords: ${keywords}

The content would be well-structured, engaging, and optimized for your intended use case. It would include proper headings, formatting, and calls to action where appropriate.

For blog posts, you'd get:
- Compelling introduction
- Well-organized body paragraphs
- Engaging conclusion
- SEO-optimized headings

For social media, you'd get:
- Platform-specific formatting
- Engaging hooks
- Relevant hashtags
- Clear calls to action

For product descriptions, you'd get:
- Benefit-focused copy
- Emotional appeal
- Clear value proposition
- Persuasive language

This content serves as a starting point that you can edit, refine, and personalize to match your exact needs and brand voice.`,
      excerpt: `AI-generated content about ${prompt} with ${tone} tone for ${targetAudience} audience.`,
      tags: keywords.split(',').map(k => k.trim()).filter(Boolean),
      wordCount: 250,
      readingTime: 2,
      createdAt: new Date(),
      prompt,
      template: contentType
    };
    
    setGeneratedContent(prev => [mockContent, ...prev]);
    setIsGenerating(false);
    onContentGenerated(mockContent);
  };

  const handleCopyContent = (content: GeneratedContent) => {
    navigator.clipboard.writeText(content.content);
    // In real app, show toast notification
  };

  const handleInsertToEditor = (content: GeneratedContent) => {
    onInsertToEditor(content);
  };

  const handleRegenerate = (originalPrompt: string) => {
    setPrompt(originalPrompt);
    generateContent();
  };

  const getContentTypeIcon = (type: string) => {
    const icons = {
      'blog-post': <FileText className="h-4 w-4" />,
      'article': <FileText className="h-4 w-4" />,
      'social-media': <MessageSquare className="h-4 w-4" />,
      'product-description': <Target className="h-4 w-4" />,
      'email-newsletter': <MessageSquare className="h-4 w-4" />
    };
    return icons[type as keyof typeof icons] || <FileText className="h-4 w-4" />;
  };

  const getReadingTime = (wordCount: number) => {
    return Math.ceil(wordCount / 200);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Wand2 className="h-5 w-5" />
            AI Content Generator
          </CardTitle>
          <CardDescription>
            Generate high-quality content using AI-powered suggestions
          </CardDescription>
        </CardHeader>
      </Card>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Generation Panel */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Create New Content</CardTitle>
            <CardDescription>
              Describe what you want to create and let AI do the work
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label htmlFor="prompt">What do you want to create?</Label>
              <Textarea
                id="prompt"
                placeholder="Describe your content idea... (e.g., 'Write a blog post about the benefits of content management systems')"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                rows={4}
                className="resize-none"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label htmlFor="contentType">Content Type</Label>
                <Select value={contentType} onValueChange={setContentType}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {templates.map(template => (
                      <SelectItem key={template.id} value={template.id}>
                        <div className="flex items-center gap-2">
                          {getContentTypeIcon(template.id)}
                          <div>
                            <div className="font-medium">{template.name}</div>
                            <div className="text-sm text-muted-foreground">
                              {template.description}
                            </div>
                          </div>
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label htmlFor="tone">Tone</Label>
                <Select value={tone} onValueChange={setTone}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="professional">Professional</SelectItem>
                    <SelectItem value="casual">Casual</SelectItem>
                    <SelectItem value="friendly">Friendly</SelectItem>
                    <SelectItem value="authoritative">Authoritative</SelectItem>
                    <SelectItem value="conversational">Conversational</SelectItem>
                    <SelectItem value="humorous">Humorous</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label htmlFor="length">Length</Label>
                <Select value={length} onValueChange={setLength}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="short">Short (100-300 words)</SelectItem>
                    <SelectItem value="medium">Medium (300-600 words)</SelectItem>
                    <SelectItem value="long">Long (600-1000 words)</SelectItem>
                    <SelectItem value="comprehensive">Comprehensive (1000+ words)</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label htmlFor="audience">Target Audience</Label>
                <Select value={targetAudience} onValueChange={setTargetAudience}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="general">General</SelectItem>
                    <SelectItem value="beginners">Beginners</SelectItem>
                    <SelectItem value="experts">Experts</SelectItem>
                    <SelectItem value="marketers">Marketers</SelectItem>
                    <SelectItem value="developers">Developers</SelectItem>
                    <SelectItem value="business">Business Owners</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div>
              <Label htmlFor="keywords">Keywords (optional)</Label>
              <Input
                id="keywords"
                placeholder="Enter keywords separated by commas..."
                value={keywords}
                onChange={(e) => setKeywords(e.target.value)}
              />
            </div>

            <Button 
              onClick={generateContent}
              disabled={!prompt.trim() || isGenerating}
              className="w-full"
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles className="h-4 w-4 mr-2" />
                  Generate Content
                </>
              )}
            </Button>

            {isGenerating && (
              <div className="space-y-2">
                <div className="flex items-center gap-2 text-sm text-muted-foreground">
                  <Brain className="h-4 w-4 animate-pulse" />
                  AI is crafting your content...
                </div>
                <Progress value={75} className="w-full" />
              </div>
            )}
          </CardContent>
        </Card>

        {/* Generated Content Panel */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Generated Content</CardTitle>
            <CardDescription>
              Your AI-generated content appears here
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4 max-h-[600px] overflow-y-auto">
              {generatedContent.length === 0 ? (
                <div className="text-center py-12 text-muted-foreground">
                  <Sparkles className="h-12 w-12 mx-auto mb-4 opacity-50" />
                  <p>No content generated yet.</p>
                  <p className="text-sm">Start by describing what you want to create.</p>
                </div>
              ) : (
                generatedContent.map((content) => (
                  <Card key={content.id} className="border-l-4 border-l-blue-500">
                    <CardHeader className="pb-3">
                      <div className="flex items-start justify-between">
                        <div className="flex-1 min-w-0">
                          <CardTitle className="text-base line-clamp-2">
                            {content.title}
                          </CardTitle>
                          <CardDescription className="text-sm">
                            {content.excerpt}
                          </CardDescription>
                          <div className="flex items-center gap-4 mt-2 text-xs text-muted-foreground">
                            <span>{content.wordCount} words</span>
                            <span>{getReadingTime(content.wordCount)} min read</span>
                            <span>{content.createdAt.toLocaleString()}</span>
                          </div>
                          {content.tags.length > 0 && (
                            <div className="flex flex-wrap gap-1 mt-2">
                              {content.tags.map(tag => (
                                <Badge key={tag} variant="secondary" className="text-xs">
                                  {tag}
                                </Badge>
                              ))}
                            </div>
                          )}
                        </div>
                        <div className="flex items-center gap-1">
                          {getContentTypeIcon(content.template)}
                        </div>
                      </div>
                    </CardHeader>
                    <CardContent className="pt-0">
                      <div className="bg-muted/30 p-3 rounded-lg mb-3 max-h-32 overflow-y-auto">
                        <p className="text-sm line-clamp-6">
                          {content.content}
                        </p>
                      </div>
                      
                      <div className="flex items-center gap-2">
                        <Button
                          size="sm"
                          onClick={() => handleInsertToEditor(content)}
                          className="flex-1"
                        >
                          <CheckCircle className="h-3 w-3 mr-1" />
                          Insert to Editor
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => handleCopyContent(content)}
                        >
                          <Copy className="h-3 w-3 mr-1" />
                          Copy
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => handleRegenerate(content.prompt)}
                        >
                          <RefreshCw className="h-3 w-3" />
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                ))
              )}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Quick Templates */}
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">Quick Templates</CardTitle>
          <CardDescription>
            Pre-built prompts for common content types
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {templates.map(template => (
              <Card key={template.id} className="cursor-pointer hover:shadow-md transition-shadow">
                <CardHeader className="pb-3">
                  <div className="flex items-center gap-2">
                    {getContentTypeIcon(template.id)}
                    <CardTitle className="text-base">{template.name}</CardTitle>
                  </div>
                  <CardDescription className="text-sm">
                    {template.description}
                  </CardDescription>
                </CardHeader>
                <CardContent className="pt-0">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => {
                      setContentType(template.id);
                      setPrompt(template.prompts[0]);
                    }}
                    className="w-full"
                  >
                    Use Template
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}